#pragma once
#include <d3d9.h>
class IDirect3DDevice9ExWrapper : public IDirect3DDevice9Ex
{
public:
	IDirect3DDevice9ExWrapper(IDirect3DDevice9Ex* RealInstance) { Real = RealInstance; }

	bool bIgnoreNextStart = false;
	bool bIgnoreNextEnd = false;

	bool bSkipWinding = false;

	// Inherited via IDirect3DDevice9Ex
	virtual __declspec(nothrow) HRESULT __stdcall QueryInterface(REFIID riid, void** ppvObj) override;
	virtual __declspec(nothrow) ULONG __stdcall AddRef(void) override;
	virtual __declspec(nothrow) ULONG __stdcall Release(void) override;
	virtual __declspec(nothrow) HRESULT __stdcall TestCooperativeLevel(void) override;
	virtual __declspec(nothrow) UINT __stdcall GetAvailableTextureMem(void) override;
	virtual __declspec(nothrow) HRESULT __stdcall EvictManagedResources(void) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetDirect3D(IDirect3D9** ppD3D9) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetDeviceCaps(D3DCAPS9* pCaps) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetDisplayMode(UINT iSwapChain, D3DDISPLAYMODE* pMode) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetCreationParameters(D3DDEVICE_CREATION_PARAMETERS* pParameters) override;
	virtual __declspec(nothrow) HRESULT __stdcall SetCursorProperties(UINT XHotSpot, UINT YHotSpot, IDirect3DSurface9* pCursorBitmap) override;
	virtual __declspec(nothrow) void __stdcall SetCursorPosition(int X, int Y, DWORD Flags) override;
	virtual __declspec(nothrow) BOOL __stdcall ShowCursor(BOOL bShow) override;
	virtual __declspec(nothrow) HRESULT __stdcall CreateAdditionalSwapChain(D3DPRESENT_PARAMETERS* pPresentationParameters, IDirect3DSwapChain9** pSwapChain) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetSwapChain(UINT iSwapChain, IDirect3DSwapChain9** pSwapChain) override;
	virtual __declspec(nothrow) UINT __stdcall GetNumberOfSwapChains(void) override;
	virtual __declspec(nothrow) HRESULT __stdcall Reset(D3DPRESENT_PARAMETERS* pPresentationParameters) override;
	virtual __declspec(nothrow) HRESULT __stdcall Present(const RECT* pSourceRect, const RECT* pDestRect, HWND hDestWindowOverride, const RGNDATA* pDirtyRegion) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetBackBuffer(UINT iSwapChain, UINT iBackBuffer, D3DBACKBUFFER_TYPE Type, IDirect3DSurface9** ppBackBuffer) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetRasterStatus(UINT iSwapChain, D3DRASTER_STATUS* pRasterStatus) override;
	virtual __declspec(nothrow) HRESULT __stdcall SetDialogBoxMode(BOOL bEnableDialogs) override;
	virtual __declspec(nothrow) void __stdcall SetGammaRamp(UINT iSwapChain, DWORD Flags, const D3DGAMMARAMP* pRamp) override;
	virtual __declspec(nothrow) void __stdcall GetGammaRamp(UINT iSwapChain, D3DGAMMARAMP* pRamp) override;
	virtual __declspec(nothrow) HRESULT __stdcall CreateTexture(UINT Width, UINT Height, UINT Levels, DWORD Usage, D3DFORMAT Format, D3DPOOL Pool, IDirect3DTexture9** ppTexture, HANDLE* pSharedHandle) override;
	virtual __declspec(nothrow) HRESULT __stdcall CreateVolumeTexture(UINT Width, UINT Height, UINT Depth, UINT Levels, DWORD Usage, D3DFORMAT Format, D3DPOOL Pool, IDirect3DVolumeTexture9** ppVolumeTexture, HANDLE* pSharedHandle) override;
	virtual __declspec(nothrow) HRESULT __stdcall CreateCubeTexture(UINT EdgeLength, UINT Levels, DWORD Usage, D3DFORMAT Format, D3DPOOL Pool, IDirect3DCubeTexture9** ppCubeTexture, HANDLE* pSharedHandle) override;
	virtual __declspec(nothrow) HRESULT __stdcall CreateVertexBuffer(UINT Length, DWORD Usage, DWORD FVF, D3DPOOL Pool, IDirect3DVertexBuffer9** ppVertexBuffer, HANDLE* pSharedHandle) override;
	virtual __declspec(nothrow) HRESULT __stdcall CreateIndexBuffer(UINT Length, DWORD Usage, D3DFORMAT Format, D3DPOOL Pool, IDirect3DIndexBuffer9** ppIndexBuffer, HANDLE* pSharedHandle) override;
	virtual __declspec(nothrow) HRESULT __stdcall CreateRenderTarget(UINT Width, UINT Height, D3DFORMAT Format, D3DMULTISAMPLE_TYPE MultiSample, DWORD MultisampleQuality, BOOL Lockable, IDirect3DSurface9** ppSurface, HANDLE* pSharedHandle) override;
	virtual __declspec(nothrow) HRESULT __stdcall CreateDepthStencilSurface(UINT Width, UINT Height, D3DFORMAT Format, D3DMULTISAMPLE_TYPE MultiSample, DWORD MultisampleQuality, BOOL Discard, IDirect3DSurface9** ppSurface, HANDLE* pSharedHandle) override;
	virtual __declspec(nothrow) HRESULT __stdcall UpdateSurface(IDirect3DSurface9* pSourceSurface, const RECT* pSourceRect, IDirect3DSurface9* pDestinationSurface, const POINT* pDestPoint) override;
	virtual __declspec(nothrow) HRESULT __stdcall UpdateTexture(IDirect3DBaseTexture9* pSourceTexture, IDirect3DBaseTexture9* pDestinationTexture) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetRenderTargetData(IDirect3DSurface9* pRenderTarget, IDirect3DSurface9* pDestSurface) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetFrontBufferData(UINT iSwapChain, IDirect3DSurface9* pDestSurface) override;
	virtual __declspec(nothrow) HRESULT __stdcall StretchRect(IDirect3DSurface9* pSourceSurface, const RECT* pSourceRect, IDirect3DSurface9* pDestSurface, const RECT* pDestRect, D3DTEXTUREFILTERTYPE Filter) override;
	virtual __declspec(nothrow) HRESULT __stdcall ColorFill(IDirect3DSurface9* pSurface, const RECT* pRect, D3DCOLOR color) override;
	virtual __declspec(nothrow) HRESULT __stdcall CreateOffscreenPlainSurface(UINT Width, UINT Height, D3DFORMAT Format, D3DPOOL Pool, IDirect3DSurface9** ppSurface, HANDLE* pSharedHandle) override;
	virtual __declspec(nothrow) HRESULT __stdcall SetRenderTarget(DWORD RenderTargetIndex, IDirect3DSurface9* pRenderTarget) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetRenderTarget(DWORD RenderTargetIndex, IDirect3DSurface9** ppRenderTarget) override;
	virtual __declspec(nothrow) HRESULT __stdcall SetDepthStencilSurface(IDirect3DSurface9* pNewZStencil) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetDepthStencilSurface(IDirect3DSurface9** ppZStencilSurface) override;
	virtual __declspec(nothrow) HRESULT __stdcall BeginScene(void) override;
	virtual __declspec(nothrow) HRESULT __stdcall EndScene(void) override;
	virtual __declspec(nothrow) HRESULT __stdcall Clear(DWORD Count, const D3DRECT* pRects, DWORD Flags, D3DCOLOR Color, float Z, DWORD Stencil) override;
	virtual __declspec(nothrow) HRESULT __stdcall SetTransform(D3DTRANSFORMSTATETYPE State, const D3DMATRIX* pMatrix) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetTransform(D3DTRANSFORMSTATETYPE State, D3DMATRIX* pMatrix) override;
	virtual __declspec(nothrow) HRESULT __stdcall MultiplyTransform(D3DTRANSFORMSTATETYPE, const D3DMATRIX*) override;
	virtual __declspec(nothrow) HRESULT __stdcall SetViewport(const D3DVIEWPORT9* pViewport) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetViewport(D3DVIEWPORT9* pViewport) override;
	virtual __declspec(nothrow) HRESULT __stdcall SetMaterial(const D3DMATERIAL9* pMaterial) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetMaterial(D3DMATERIAL9* pMaterial) override;
	virtual __declspec(nothrow) HRESULT __stdcall SetLight(DWORD Index, const D3DLIGHT9*) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetLight(DWORD Index, D3DLIGHT9*) override;
	virtual __declspec(nothrow) HRESULT __stdcall LightEnable(DWORD Index, BOOL Enable) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetLightEnable(DWORD Index, BOOL* pEnable) override;
	virtual __declspec(nothrow) HRESULT __stdcall SetClipPlane(DWORD Index, const float* pPlane) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetClipPlane(DWORD Index, float* pPlane) override;
	virtual __declspec(nothrow) HRESULT __stdcall SetRenderState(D3DRENDERSTATETYPE State, DWORD Value) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetRenderState(D3DRENDERSTATETYPE State, DWORD* pValue) override;
	virtual __declspec(nothrow) HRESULT __stdcall CreateStateBlock(D3DSTATEBLOCKTYPE Type, IDirect3DStateBlock9** ppSB) override;
	virtual __declspec(nothrow) HRESULT __stdcall BeginStateBlock(void) override;
	virtual __declspec(nothrow) HRESULT __stdcall EndStateBlock(IDirect3DStateBlock9** ppSB) override;
	virtual __declspec(nothrow) HRESULT __stdcall SetClipStatus(const D3DCLIPSTATUS9* pClipStatus) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetClipStatus(D3DCLIPSTATUS9* pClipStatus) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetTexture(DWORD Stage, IDirect3DBaseTexture9** ppTexture) override;
	virtual __declspec(nothrow) HRESULT __stdcall SetTexture(DWORD Stage, IDirect3DBaseTexture9* pTexture) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetTextureStageState(DWORD Stage, D3DTEXTURESTAGESTATETYPE Type, DWORD* pValue) override;
	virtual __declspec(nothrow) HRESULT __stdcall SetTextureStageState(DWORD Stage, D3DTEXTURESTAGESTATETYPE Type, DWORD Value) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetSamplerState(DWORD Sampler, D3DSAMPLERSTATETYPE Type, DWORD* pValue) override;
	virtual __declspec(nothrow) HRESULT __stdcall SetSamplerState(DWORD Sampler, D3DSAMPLERSTATETYPE Type, DWORD Value) override;
	virtual __declspec(nothrow) HRESULT __stdcall ValidateDevice(DWORD* pNumPasses) override;
	virtual __declspec(nothrow) HRESULT __stdcall SetPaletteEntries(UINT PaletteNumber, const PALETTEENTRY* pEntries) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetPaletteEntries(UINT PaletteNumber, PALETTEENTRY* pEntries) override;
	virtual __declspec(nothrow) HRESULT __stdcall SetCurrentTexturePalette(UINT PaletteNumber) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetCurrentTexturePalette(UINT* PaletteNumber) override;
	virtual __declspec(nothrow) HRESULT __stdcall SetScissorRect(const RECT* pRect) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetScissorRect(RECT* pRect) override;
	virtual __declspec(nothrow) HRESULT __stdcall SetSoftwareVertexProcessing(BOOL bSoftware) override;
	virtual __declspec(nothrow) BOOL __stdcall GetSoftwareVertexProcessing(void) override;
	virtual __declspec(nothrow) HRESULT __stdcall SetNPatchMode(float nSegments) override;
	virtual __declspec(nothrow) float __stdcall GetNPatchMode(void) override;
	virtual __declspec(nothrow) HRESULT __stdcall DrawPrimitive(D3DPRIMITIVETYPE PrimitiveType, UINT StartVertex, UINT PrimitiveCount) override;
	virtual __declspec(nothrow) HRESULT __stdcall DrawIndexedPrimitive(D3DPRIMITIVETYPE, INT BaseVertexIndex, UINT MinVertexIndex, UINT NumVertices, UINT startIndex, UINT primCount) override;
	virtual __declspec(nothrow) HRESULT __stdcall DrawPrimitiveUP(D3DPRIMITIVETYPE PrimitiveType, UINT PrimitiveCount, const void* pVertexStreamZeroData, UINT VertexStreamZeroStride) override;
	virtual __declspec(nothrow) HRESULT __stdcall DrawIndexedPrimitiveUP(D3DPRIMITIVETYPE PrimitiveType, UINT MinVertexIndex, UINT NumVertices, UINT PrimitiveCount, const void* pIndexData, D3DFORMAT IndexDataFormat, const void* pVertexStreamZeroData, UINT VertexStreamZeroStride) override;
	virtual __declspec(nothrow) HRESULT __stdcall ProcessVertices(UINT SrcStartIndex, UINT DestIndex, UINT VertexCount, IDirect3DVertexBuffer9* pDestBuffer, IDirect3DVertexDeclaration9* pVertexDecl, DWORD Flags) override;
	virtual __declspec(nothrow) HRESULT __stdcall CreateVertexDeclaration(const D3DVERTEXELEMENT9* pVertexElements, IDirect3DVertexDeclaration9** ppDecl) override;
	virtual __declspec(nothrow) HRESULT __stdcall SetVertexDeclaration(IDirect3DVertexDeclaration9* pDecl) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetVertexDeclaration(IDirect3DVertexDeclaration9** ppDecl) override;
	virtual __declspec(nothrow) HRESULT __stdcall SetFVF(DWORD FVF) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetFVF(DWORD* pFVF) override;
	virtual __declspec(nothrow) HRESULT __stdcall CreateVertexShader(const DWORD* pFunction, IDirect3DVertexShader9** ppShader) override;
	virtual __declspec(nothrow) HRESULT __stdcall SetVertexShader(IDirect3DVertexShader9* pShader) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetVertexShader(IDirect3DVertexShader9** ppShader) override;
	virtual __declspec(nothrow) HRESULT __stdcall SetVertexShaderConstantF(UINT StartRegister, const float* pConstantData, UINT Vector4fCount) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetVertexShaderConstantF(UINT StartRegister, float* pConstantData, UINT Vector4fCount) override;
	virtual __declspec(nothrow) HRESULT __stdcall SetVertexShaderConstantI(UINT StartRegister, const int* pConstantData, UINT Vector4iCount) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetVertexShaderConstantI(UINT StartRegister, int* pConstantData, UINT Vector4iCount) override;
	virtual __declspec(nothrow) HRESULT __stdcall SetVertexShaderConstantB(UINT StartRegister, const BOOL* pConstantData, UINT BoolCount) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetVertexShaderConstantB(UINT StartRegister, BOOL* pConstantData, UINT BoolCount) override;
	virtual __declspec(nothrow) HRESULT __stdcall SetStreamSource(UINT StreamNumber, IDirect3DVertexBuffer9* pStreamData, UINT OffsetInBytes, UINT Stride) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetStreamSource(UINT StreamNumber, IDirect3DVertexBuffer9** ppStreamData, UINT* pOffsetInBytes, UINT* pStride) override;
	virtual __declspec(nothrow) HRESULT __stdcall SetStreamSourceFreq(UINT StreamNumber, UINT Setting) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetStreamSourceFreq(UINT StreamNumber, UINT* pSetting) override;
	virtual __declspec(nothrow) HRESULT __stdcall SetIndices(IDirect3DIndexBuffer9* pIndexData) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetIndices(IDirect3DIndexBuffer9** ppIndexData) override;
	virtual __declspec(nothrow) HRESULT __stdcall CreatePixelShader(const DWORD* pFunction, IDirect3DPixelShader9** ppShader) override;
	virtual __declspec(nothrow) HRESULT __stdcall SetPixelShader(IDirect3DPixelShader9* pShader) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetPixelShader(IDirect3DPixelShader9** ppShader) override;
	virtual __declspec(nothrow) HRESULT __stdcall SetPixelShaderConstantF(UINT StartRegister, const float* pConstantData, UINT Vector4fCount) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetPixelShaderConstantF(UINT StartRegister, float* pConstantData, UINT Vector4fCount) override;
	virtual __declspec(nothrow) HRESULT __stdcall SetPixelShaderConstantI(UINT StartRegister, const int* pConstantData, UINT Vector4iCount) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetPixelShaderConstantI(UINT StartRegister, int* pConstantData, UINT Vector4iCount) override;
	virtual __declspec(nothrow) HRESULT __stdcall SetPixelShaderConstantB(UINT StartRegister, const BOOL* pConstantData, UINT BoolCount) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetPixelShaderConstantB(UINT StartRegister, BOOL* pConstantData, UINT BoolCount) override;
	virtual __declspec(nothrow) HRESULT __stdcall DrawRectPatch(UINT Handle, const float* pNumSegs, const D3DRECTPATCH_INFO* pRectPatchInfo) override;
	virtual __declspec(nothrow) HRESULT __stdcall DrawTriPatch(UINT Handle, const float* pNumSegs, const D3DTRIPATCH_INFO* pTriPatchInfo) override;
	virtual __declspec(nothrow) HRESULT __stdcall DeletePatch(UINT Handle) override;
	virtual __declspec(nothrow) HRESULT __stdcall CreateQuery(D3DQUERYTYPE Type, IDirect3DQuery9** ppQuery) override;
	virtual __declspec(nothrow) HRESULT __stdcall SetConvolutionMonoKernel(UINT width, UINT height, float* rows, float* columns) override;
	virtual __declspec(nothrow) HRESULT __stdcall ComposeRects(IDirect3DSurface9* pSrc, IDirect3DSurface9* pDst, IDirect3DVertexBuffer9* pSrcRectDescs, UINT NumRects, IDirect3DVertexBuffer9* pDstRectDescs, D3DCOMPOSERECTSOP Operation, int Xoffset, int Yoffset) override;
	virtual __declspec(nothrow) HRESULT __stdcall PresentEx(const RECT* pSourceRect, const RECT* pDestRect, HWND hDestWindowOverride, const RGNDATA* pDirtyRegion, DWORD dwFlags) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetGPUThreadPriority(INT* pPriority) override;
	virtual __declspec(nothrow) HRESULT __stdcall SetGPUThreadPriority(INT Priority) override;
	virtual __declspec(nothrow) HRESULT __stdcall WaitForVBlank(UINT iSwapChain) override;
	virtual __declspec(nothrow) HRESULT __stdcall CheckResourceResidency(IDirect3DResource9** pResourceArray, UINT32 NumResources) override;
	virtual __declspec(nothrow) HRESULT __stdcall SetMaximumFrameLatency(UINT MaxLatency) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetMaximumFrameLatency(UINT* pMaxLatency) override;
	virtual __declspec(nothrow) HRESULT __stdcall CheckDeviceState(HWND hDestinationWindow) override;
	virtual __declspec(nothrow) HRESULT __stdcall CreateRenderTargetEx(UINT Width, UINT Height, D3DFORMAT Format, D3DMULTISAMPLE_TYPE MultiSample, DWORD MultisampleQuality, BOOL Lockable, IDirect3DSurface9** ppSurface, HANDLE* pSharedHandle, DWORD Usage) override;
	virtual __declspec(nothrow) HRESULT __stdcall CreateOffscreenPlainSurfaceEx(UINT Width, UINT Height, D3DFORMAT Format, D3DPOOL Pool, IDirect3DSurface9** ppSurface, HANDLE* pSharedHandle, DWORD Usage) override;
	virtual __declspec(nothrow) HRESULT __stdcall CreateDepthStencilSurfaceEx(UINT Width, UINT Height, D3DFORMAT Format, D3DMULTISAMPLE_TYPE MultiSample, DWORD MultisampleQuality, BOOL Discard, IDirect3DSurface9** ppSurface, HANDLE* pSharedHandle, DWORD Usage) override;
	virtual __declspec(nothrow) HRESULT __stdcall ResetEx(D3DPRESENT_PARAMETERS* pPresentationParameters, D3DDISPLAYMODEEX* pFullscreenDisplayMode) override;
	virtual __declspec(nothrow) HRESULT __stdcall GetDisplayModeEx(UINT iSwapChain, D3DDISPLAYMODEEX* pMode, D3DDISPLAYROTATION* pRotation) override;

protected:
	IDirect3DDevice9Ex* Real;
};

